# Generated by Django 4.1.3 on 2022-11-22 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, default='T-shirt', on_delete=django.db.models.deletion.CASCADE, to='product.categories'),
        ),
    ]
