# Generated by Django 4.1.3 on 2022-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearning',
            name='image',
            field=models.ImageField(upload_to='output'),
        ),
        migrations.AlterField(
            model_name='machinelearning',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
