# Generated by Django 4.1.3 on 2022-11-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_products_bookmark_alter_products_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_image", models.ImageField(upload_to="%y/%m/")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.categories",
                    ),
                ),
            ],
        ),
    ]
