# Generated by Django 4.1.3 on 2022-11-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0002_alter_comments_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True, related_name="add_bookmark", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="User_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_image", models.ImageField(upload_to="%y/%m/")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.categories",
                    ),
                ),
            ],
        ),
    ]
