# Generated by Django 4.1.3 on 2022-11-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_products_bookmark_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
