# Generated by Django 4.1.3 on 2022-11-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profilename',
            field=models.CharField(blank=True, default='-', max_length=30, verbose_name='회원이름'),
        ),
    ]
