# Generated by Django 4.1.3 on 2022-11-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
